FROM vdubois/java-oracle:1.7u80

RUN apt-get update \
  && apt-get install -y curl --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV MAVEN_VERSION 3.3.9

RUN mkdir -p /usr/share/maven-$MAVEN_VERSION \
  && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven-$MAVEN_VERSION --strip-components=1 \
  && ln -s /usr/share/maven-$MAVEN_VERSION/bin/mvn /usr/bin/mvn

RUN export uid=1001 gid=1001 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    mkdir -p /etc/sudoers.d/ && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer && \
    chown ${uid}:${gid} -R /usr/share/maven-3.3.9

USER developer

ENV MAVEN_HOME /usr/share/maven-3.3.9

CMD ["mvn"]
